apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-app
  namespace: wexa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-pod
  template:
    metadata:
      labels:
        app: portfolio-pod
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
        - name: portfolio-cont
          image: ghcr.io/venkatasureshborra/portfolio:v1.0 
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
